# Project Name
TARGET = PV_tester

# Sources
CPP_SOURCES = PV_tester.cpp

#Utils
C_INCLUDES = -I ../../Utils/  \
-I../../../ChowDSP/include/math_approx/ \
-Istmlib/

# Library Locations
LIBDAISY_DIR = ../../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
