# Project Name
TARGET = Non_Lin_Algs

# Sources
CPP_SOURCES = Non_Lin_Algs.cpp highshelf.cpp

# Library Locations
LIBDAISY_DIR = ../../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
