# Project Name
TARGET = FFT_tester

# Sources
CPP_SOURCES = FFT_tester.cpp

#Utils
C_INCLUDES = -I ../../Utils/

# Library Locations
LIBDAISY_DIR = ../../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
