# Project Name
TARGET = Midi_Sidechain_Comp

USE_DAISYSP_LGPL=1
LDFLAGS += -u _printf_float

# Sources
CPP_SOURCES = Midi_Sidechain_Comp.cpp

# Library Locations
LIBDAISY_DIR = ../../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
